version: '3.9'

networks:
  bookstore_network:
    driver: bridge

services:
  db:
    image: postgres:15
    networks:
      - bookstore_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1896
      - POSTGRES_DB=bookstore_db

  web:
    build: .
    command: sh -c "while ! pg_isready -h db -p 5432 -U postgres; do sleep 1; done && python manage.py runserver 0.0.0.0:8000"
    networks:
      - bookstore_network
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    depends_on:
      - db
