services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_NAME=bookstore_db
      - DATABASE_USER=bookstore_user
      - DATABASE_PASSWORD=bookstore_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_pass

volumes:
  postgres_data:
