name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    matrix:
      python-version: [ 3.12 ]
    steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Upgrade pip
          run: python -m pip install --upgrade pip

        - name: Install Poetry
          run: |
            pip install poetry==1.4.1
            poetry --version

        - name: Install dependencies
          run: poetry install

        - name: Run Tests
          run: poetry run pytest --cov=.