name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: 'csar.santos18@gmail.com'

      - name: Instalar Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Executar migrações Django no Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run python manage.py migrate -a ${{ secrets.HEROKU_APP_NAME }}
